### ISSUE TITLE
extractaudio function missed in package

### ISSUE THREAD

**Issue by YuhengF** [WALIII/ImBat#50]
I'm running the package on ubuntu 22.04 and cloned FinchScope (Liberti tree of the original repo) as well as other dependencies. When running FS_AV_Parse_batch.m, it calls extractmedia() (in FinchScope repo), but another function extractaudio (line 12 of extractmedia) is missed. According to the annotation above this calling, extractaudio should be a mex file and do find this extractaudio.mexmaci64. But I couldn't process this file.

**Comment by WALIII** [comment]
Comment here for posterity: this is a compile for the AVfoundation framework which is mac specific- there is a note about this already in the comments of `FS_AV_Parse_batch.m`. There are currently no plans to build alternative functions that are cross platform.

I'm going to mark as resolved for now
